services:
  - type: web
    name: tablaspollet
    runtime: static
    buildCommand: echo "Sitio estatico, CSV ya generados en web/data"
    staticPublishPath: ./web
    headers:
      - path: /data/*
        name: Cache-Control
        value: no-cache
